---
title: "class11.3"
format: pdf
---


Here we analyze our AlphaFold structure prediction models. The input directory/folder comes from the ColabFold server:

```{r}
# Change this for YOUR results dir name
results_dir <- "find_a_gene_pt2_e7274/"
```

```{r}
# File names for all PDB models
pdb_files <- list.files(path=results_dir,
                        pattern="*.pdb",
                        full.names = TRUE)

# Print our PDB file names
basename(pdb_files)
```

I will use the Bio3D package for analysis

```{r}
library(bio3d)
```

Align and Superpose

```{r}
# Read all data from Models 
#  and superpose/fit coords
pdbs <- pdbaln(pdb_files, fit=TRUE, exefile="msa")
pdbs
```




Experimenting:

```{r}
aln_file <- list.files(path=results_dir,
                       pattern=".a3m$",
                        full.names = TRUE)
aln_file
```

```{r}
aln <- read.fasta(aln_file[1], to.upper = TRUE)
```


```{r}
dim(aln$ali)
```


```{r}
sim <- conserv(aln)
```

```{r}
plotb3(sim[1:99], sse=trim.pdb(pdb, chain="A"),
       ylab="Conservation Score")
```


```{r}
con <- consensus(aln, cutoff = 0.6)
con$seq
```

```{r}
m1.pdb <- read.pdb(pdb_files[1])
occ <- vec2resno(c(sim[1:99], sim[1:99]), m1.pdb$atom$resno)
write.pdb(m1.pdb, o=occ, file="m1_conserv.pdb")
```




